const fs=require('fs'),vm=require('vm');
const s={console,window:null,JSON,Date};s.window=s;s.HaghyarLawyerBrief={aiReady:c=>({schema:'HaghyarAIReady/2.0',case:{identity:{case_id:c.id},classification:{domain:c.domain},facts:{goal:{label:'خواسته',value:c.answers&&c.answers.goal&&c.answers.goal.value,state:'KNOWN'}},timeline:[{date:'1405/01/01',title:'رویداد آزمایشی'}],evidence:[{title:'مدرک آزمایشی',status:'available'}],unknowns:[],contradictions:c.contradictions||[]}})};vm.createContext(s);vm.runInContext(fs.readFileSync('app/src/main/assets/v2_ai_actions.js','utf8'),s);
let fail=[],A=s.DanjurAIActions,domains=['property','family','debt','work','contract','criminal','business','other'];function ok(x,m){if(!x)fail.push(m)}
ok(A&&A.domains.length===8,'engine must cover 8 domains');
const required={property:['notice','petition'],family:['petition','defense'],debt:['notice','petition'],work:['labor_claim','defense'],contract:['notice','contract_draft'],criminal:['complaint','criminal_defense'],business:['commercial_notice','contract_draft'],other:['notice','request']};
for(const d of domains){let acts=A.actions(d),ids=acts.map(x=>x.id);ok(acts.length>=8,d+' action catalog too small');for(const id of required[d])ok(ids.includes(id),d+' missing '+id);for(const id of ['analysis','next_steps','evidence_review','lawyer_summary'])ok(ids.includes(id),d+' missing common '+id);let c={id:'DJ-QA-'+d,domain:d,answers:{goal:{value:'خواسته آزمایشی'}},readiness:{blockers:[]},contradictions:[]};for(const a of acts){let p=A.build(c,a.id),serialized=JSON.stringify(p);ok(p.schema==='DanjurAIPrompt/1.0',d+' schema');ok(p.request.action_id===a.id,d+' action identity');ok(p.prompt.includes(a.title),d+' prompt title '+a.id);ok(p.prompt.includes('هیچ واقعیت'),d+' anti-fabrication '+a.id);ok(p.prompt.includes('حقوق ایران'),d+' jurisdiction '+a.id);ok(p.case&&p.case.identity&&p.case.identity.case_id===c.id,d+' missing case identity '+a.id);ok(serialized.includes('خواسته آزمایشی'),d+' missing case facts '+a.id);ok(p.prompt.includes('DJ-QA-'+d)&&p.prompt.includes('رویداد آزمایشی')&&p.prompt.includes('مدرک آزمایشی'),d+' prompt is not carrying case context '+a.id)}}
let criminal=A.build({id:'DJ-C',domain:'criminal',answers:{},readiness:{blockers:[]},contradictions:[]},'complaint');ok(criminal.prompt.includes('واقعیت اثبات‌شده'), 'criminal neutrality missing');
let blocked=A.build({id:'DJ-B',domain:'property',answers:{},readiness:{blockers:[{message:'اطلاعات بحرانی ناقص'}]},contradictions:[{hard:true,message:'تناقض سخت'}]},'notice');ok(blocked.preflight.ready_for_ai===false,'hard preflight must block ready flag');ok(blocked.prompt.includes('اطلاعات بحرانی ناقص')&&blocked.prompt.includes('تناقض سخت'),'preflight issues absent from prompt');
let ui=fs.readFileSync('app/src/main/assets/v2_ai_ui.js','utf8'),about=fs.readFileSync('app/src/main/assets/v2_about.js','utf8');ok(ui.includes('packageIncludesCase:true')&&ui.includes('بسته کامل AI شامل پرامپ و اطلاعات پرونده'),'AI UI must export prompt + case context');ok(ui.includes("DANJUR-AI-")&&ui.includes("'application/json'"),'AI UI export formats missing');ok(about.includes("a.src='v2_ai_actions.js'")&&about.includes("u.src='v2_ai_ui.js'"),'AI engine/UI not loaded by runtime bootstrap');
console.log(JSON.stringify({suite:'DANJUR AI Actions',domains:domains.length,domainActions:Object.fromEntries(domains.map(d=>[d,A.actions(d).length])),contextRequired:true,uiWired:true,failures:fail},null,2));if(fail.length)process.exit(2);