const fs=require('fs'),vm=require('vm');
function n(){return {innerHTML:'',textContent:'',value:'',style:{},dataset:{},children:[],classList:{add(){},remove(){},toggle(){}},appendChild(x){this.children.push(x);return x},insertBefore(x){this.children.push(x);return x},querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},setAttribute(){},closest(){return null}}}
const nodes=new Map(),document={head:n(),body:n(),getElementById(id){if(!nodes.has(id))nodes.set(id,n());return nodes.get(id)},querySelector(){return null},querySelectorAll(){return[]},createElement(){return n()},addEventListener(){}};
const store={},localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]};
const s={console,document,localStorage,Date,JSON,Math,Number,String,Array,Object,RegExp,Intl,setTimeout:f=>{if(f)f()},clearTimeout(){},alert(){}};s.window=s;s.globalThis=s;s.scrollTo=()=>{};vm.createContext(s);
let html=fs.readFileSync('app/src/main/assets/v1_1.html','utf8'),m=html.match(/<script>([\s\S]*)<\/script>/);if(!m)throw Error('base script missing');let base=m[1].replace(/\binit\(\);\s*$/,'');vm.runInContext(base+'\n;globalThis.QA_C=C;globalThis.QA_COMMON=COMMON;globalThis.QA_T=T;',s);
vm.runInContext(fs.readFileSync('app/src/main/assets/v1_2_patch.js','utf8'),s);vm.runInContext('globalThis.QA_T=T;',s);vm.runInContext(fs.readFileSync('app/src/main/assets/v2_help.js','utf8'),s);
const sets={};for(const d of Object.keys(s.QA_C))sets[d]=[].concat(s.QA_COMMON,s.QA_T[d]||[]);const a=s.HaghyarHelp.audit(sets);let bad=[];if(!a.ok)bad.push(...a.missingQuestions,...a.missingOptions);for(const d of Object.keys(sets))for(const q of sets[d]){let h=s.HaghyarHelp.question(q.id,d);if(!h||!h.why||h.why.length<20)bad.push('question:'+d+':'+q.id);for(const o of q.o||[]){let x=s.HaghyarHelp.option(q.id,o,d);if(!x||!x.text||x.text.length<30)bad.push('option:'+d+':'+q.id+':'+o)}}
console.log(JSON.stringify({suite:'Haghyar Help Coverage',domains:Object.keys(sets).length,questions:a.questions,options:a.options,ok:bad.length===0,failures:bad.slice(0,30)},null,2));if(Object.keys(sets).length!==8||a.questions!==192||a.options!==751||bad.length)process.exit(2);
