const fs=require('fs'),vm=require('vm');
const files=p=>fs.readFileSync(p,'utf8');
const base=files('app/src/main/assets/v1_1.html'),help=files('app/src/main/assets/v2_help.js'),ui=files('app/src/main/assets/v2_commercial_ui.js'),post=files('app/src/main/assets/v2_post_integration.js'),about=files('app/src/main/assets/v2_about.js'),brief=files('app/src/main/assets/v2_lawyer_brief.js'),manifest=files('app/src/main/AndroidManifest.xml'),main=files('app/src/main/java/ir/haghyar/offline/MainActivity.java');
let fail=[],checks=0;function ok(v,m){checks++;if(!v)fail.push(m)}
const domains=['property','family','debt','work','contract','criminal','business','other'];
ok(/function\s+next\s*\(/.test(base),'next() runtime missing');ok(/function\s+prev\s*\(/.test(base),'prev() runtime missing');ok(/onclick="next\(\)"/.test(base),'Next button not wired');ok(/onclick="prev\(\)"/.test(base),'Back button not wired');
for(const d of domains)ok(new RegExp('(?:const C=\\{|,)'+d+':\\[').test(base),'domain missing '+d);ok(/Object\.entries\(C\)|Object\.keys\(C\)/.test(base),'domain cards are not generated from C');
ok(/function\s+openHelp\s*\(/.test(help),'openHelp missing');ok(/H\.question\(/.test(help)||/H\.registry\[z\.id\]/.test(help),'question help registry lookup missing');ok(/H\.option\(/.test(help),'option help registry lookup missing');ok(/hyHelp2Btn/.test(help)&&/hyHelp2Option/.test(help),'help controls missing');ok(/onclick=function\(e\)/.test(help),'help click event missing');ok(/remove\(\)|display\s*=\s*['"]none/.test(help),'help close behavior missing');
ok(/window\.hyResume\s*=/.test(ui),'base hyResume missing');ok(/function\s+restoreDraft\s*\(/.test(ui),'base restoreDraft missing');ok(/function\s+installResume\s*\(/.test(post)&&/robustResume:true/.test(post),'robust resume layer missing');ok(/H\.cases\.load\(id\)/.test(post),'resume active case fallback missing');ok(/H\.cases\.list\?H\.cases\.list\(\)/.test(post),'resume recent case fallback missing');ok(/restoreState\(x\.legacyState,x\.id\)/.test(post),'resume legacy state recovery missing');
ok(/B\.aiReady\(rc\)/.test(post),'AI-ready builder not invoked');ok(/window\.hyExport\s*=/.test(post),'export wrapper missing');ok(/share\.redactions/.test(post),'redaction metadata missing');ok(/x\.evidence=\[\];x\.attachments=\[\]/.test(post),'attachment redaction incomplete');
ok(/savePdf/.test(ui)&&/saveDocx/.test(ui)&&/saveZip/.test(ui),'PDF/DOCX/ZIP export bridge missing');ok(/DANJUR-/.test(ui),'DANJUR export filenames missing');ok(/aiReady/.test(post),'AI-ready export contract missing');ok(/case-ai-ready\.json/.test(main)&&/lawyer-brief\.txt/.test(main),'ZIP export contract incomplete');
ok(/appLockAvailable/.test(post)&&/setAppLock/.test(post)&&/lockNow/.test(post),'app lock UI bridge missing');ok(/enabled=!!\(a&&a\.appLockEnabled&&a\.appLockEnabled\(\)\)/.test(post),'app lock callback does not query native truth');ok(!/state==='cancelled'\)t\.checked=false/.test(post),'cancelled auth can incorrectly disable UI state');
const order=['v2_commercial_core.js','v2_help.js','v2_lawyer_brief.js','v2_commercial_ui.js','v2_post_integration.js','v2_about.js'].map(x=>main.indexOf(x));ok(order.every(x=>x>=0)&&order.every((x,i)=>i===0||x>order[i-1]),'Android patch load order invalid');ok(/setVisibility\(View\.INVISIBLE\)/.test(main),'locked WebView is not hidden');ok(/authenticateForUnlock/.test(main),'unlock authentication missing');ok(/onStop\(\)/.test(main)&&/authenticated=false/.test(main),'background relock lifecycle missing');ok(/disableAppLock\(\)/.test(main)&&/غیرفعال‌سازی قفل دانژور/.test(main),'disable lock re-auth missing');
ok(/window\.hyAbout\s*=/.test(about),'About route missing');ok(/درباره دانژور و راهنمای استفاده/.test(about),'About home action missing');ok(/دانژور چه کارهایی انجام می‌دهد/.test(about),'About capabilities missing');ok(/چطور نتیجه بهتری بگیرید/.test(about),'About usage guidance missing');ok(/با خروجی دانژور چه کار می‌توانید بکنید/.test(about),'About output guidance missing');ok(/نام «دانژور» از کجا آمده/.test(about),'About brand explanation missing');ok(/بدان\. بپرس\. پیش برو\./.test(about),'final DANJUR tagline missing');
ok(/android:label="دانژور"/.test(manifest),'Android visible app label is not DANJUR');ok(/دانژور/.test(brief),'Lawyer Brief not rebranded to DANJUR');
const visible=[manifest,ui,about,brief];ok(!visible.some(x=>/حق[‌ ]?یار/.test(x)),'old Haghyar brand remains in visible release surfaces');
const legacy=files('app/src/main/assets/v1_6_ui_fix.js');ok(!/hyq16|hyHelp16/.test(legacy),'legacy duplicate help UI returned');
console.log(JSON.stringify({suite:'DANJUR Runtime Interaction Regression',domains:domains.length,checks,failed:fail.length,failures:fail},null,2));if(fail.length)process.exit(2);
